#!/bin/bash

# This version of backitup is meant for use prior to reformatting.
# It backs up some additional directories to the ~/Desktop/backup folder on the remote computer.

# usage: $ sh ./backitup
# or, to sync with delete, $ sh ./backitup delete


if [[ $1 == "delete" ]]
then
	echo "Are you sure you want to rsync with the delete flag? y/n"
	read a
	if [[ $a == "Y" || $a == "y" ]]; then
		rsync -avu --progress --delete ~/Desktop/work ftseng@pony.local:~/Desktop/repos
		rsync -avu --progress --delete ~/Desktop/projects ftseng@pony.local:~/Desktop/repos
		rsync -avu --progress --delete ~/Desktop/STUFF ftseng@pony.local:~/Desktop/repos
		rsync -avu --progress --delete ~/Desktop/graphics ftseng@pony.local:~/Desktop/repos
		rsync -avu --progress --delete ~/Desktop/informations ftseng@pony.local:~/Desktop/repos

        # To ~/Desktop/backup on remote computer.
		rsync -avu --progress --delete ~/Downloads ftseng@pony.local:~/Desktop/backup
        cp -r ~/.ssh ~/ssh
		rsync -avu --progress --delete ~/ssh ftseng@pony.local:~/Desktop/backup
        rm -rf ~/ssh

		echo "Pushing backups to outerspace HDD..."
	echo "Please provide password for ftseng@pony.local"
	now=$(date +"%m_%d_%Y" | tr -d "\n")
	ssh ftseng@pony.local "sed -i '' -e '1s/.*/'$now'/' ~/Desktop/repos/_lastupdated.txt; bash backitup delete"
	else
	  echo "Not doing it"
	fi
else
	rsync -avu --progress ~/Desktop/work ftseng@pony.local:~/Desktop/repos
	rsync -avu --progress ~/Desktop/projects ftseng@pony.local:~/Desktop/repos
	rsync -avu --progress ~/Desktop/STUFF ftseng@pony.local:~/Desktop/repos
	rsync -avu --progress ~/Desktop/graphics ftseng@pony.local:~/Desktop/repos
	rsync -avu --progress ~/Desktop/informations ftseng@pony.local:~/Desktop/repos

    # To ~/Desktop/backup on remote computer.
    rsync -avu --progress --delete ~/Downloads ftseng@pony.local:~/Desktop/backup

	echo "Pushing backups to outerspace HDD..."
	echo "Please provide password for ftseng@pony.local"
	now=$(date +"%m_%d_%Y" | tr -d "\n")
	ssh ftseng@pony.local "sed -i '' -e '1s/.*/'$now'/' ~/Desktop/repos/_lastupdated.txt; bash backitup"
fi
